apiVersion: sops.maesh.dev/v1alpha1
kind: SopsSecret
metadata:
    labels:
        app.kubernetes.io/name: sops-secret-operator
        app.kubernetes.io/managed-by: kustomize
    name: sopssecret-sample
    namespace: default
spec:
    decryption:
        pgp:
            keyRef:
                name: pgp-key
                key: pgp.asc
                namespace: default
            passphraseRef:
                name: pgp-key
                key: passphrase
                namespace: default
data:
    secret-password: ENC[AES256_GCM,data:anKXwdg4OUYlVVyF,iv:78h371syQFYf4GWTMiml5uzZlSs3pQfdSVP9UQCgEIw=,tag:u8+cqsJGmxjaUUsIMeJyxg==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T19:27:24Z"
    mac: ENC[AES256_GCM,data:73gfNoH9TM/0kYFa9QZDMBcxJimQz0kK71oMfUQftUmIvlqpGqF5r/jkrXhSbgYfbNZmJMPFDwynW53xeqDHPmmetu/7M150Fxn3FkdPbj4508AxFFDSOpUgk/qUGvijAwteRY0p12hyu2rTYxM65UqmVxg/9eUY8v+Z9ButA8Y=,iv:gcKJ7QVc18HDZwop899vPcqJRRC9koaoNHvlQIV7jTc=,tag:JpgIs68GA3Rec+Jw5PzBBA==,type:str]
    pgp:
        - created_at: "2026-09-12T19:27:24Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DyBxn5U0qi3MSAQdAvwkrbB3x/jhfHUvIjIQkD/KBBaXYkwwe7lISlfNiMFow
            mRWc8JPvz72Xy0pmp8lIgRModYsDaTaKlCT/X7xD7Q7gXlE38GslHv9mfSJJ8VNT
            0l4BYLB+QaSqS6D1kjsXQawfXHRg7jYajb349s3Wjslw0I6KuT2QV+fc6+BtJT5/
            MxRH3XrsJTnRX8erLI0B9Qd5yGPXzVH6q3KPQyt8LO9/zpGW7opD+pCMZOGukh2o
            =5KOe
            -----END PGP MESSAGE-----
          fp: 4326ED081E26332663FE62594484F990D5068F20
    version: 3.13.3
